spring.application.name=customer-manager
#tag::profile-config[]
# only activate profile local, when running from locally
spring.config.import=optional:file:./spring.profiles.active.local.properties
#end::profile-config[]
