stages:
  - build
  - integration-test

services:
  - name: docker:dind
    # explicitly disable tls to avoid docker startup interruption
    command: ["--tls=false"]

variables:
  # Instruct Testcontainers to use the daemon of DinD, use port 2375 for non-tls connections.
  DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: maven
  paths:
    - .m2/repository

maven-build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21
  before_script:
    - echo api.version=1.44 >> ~/.docker-java.properties
  script:
    - mvn clean install
  artifacts:
    paths:
      - basisprojekt-server/target/
    expire_in: 1 week

docker-compose:
  stage: integration-test
  image: docker:cli
  before_script:
    - apk add --no-cache curl
  script:
    - echo "Starting docker-compose..."
    - docker-compose up -d
    - echo "Testing Start Page..."
    - RESPONSE=$(curl --retry 20 --retry-all-errors -sf http://docker:8080/)
    - echo "$RESPONSE" | grep -q "Basisprojekt" || (echo "❌ index.html not found!"; exit 1)
    - echo "✅ Start Page found";
    - echo "Testing REST Call..."
    - RESPONSE=$(curl -sf http://docker:8080/api/counters/example)
    - echo "$RESPONSE" | grep -q "42" || (echo "❌ Counter not found!"; exit 1)
    - echo "✅ Counter found."
  after_script:
    - docker compose down
