image: maven:3.9.9-eclipse-temurin-21

stages:
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: maven
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn clean install
  artifacts:
    paths:
      - basisprojekt-server/target/
    expire_in: 1 week
