services:
# tag::database[]
  database:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: geheim
    ports:
      - 5432:5432

  flyway:
    image: flyway/flyway:10.22
    command: migrate -locations=filesystem:/flyway/sql,filesystem:/flyway/testdata -user=postgres -password=geheim -connectRetries=60 -url=jdbc:postgresql://database:5432/postgres
    depends_on:
      database:
        condition: service_started
    volumes:
      - ./customer-manager-server/src/main/resources/db/migration:/flyway/sql
      - ./customer-manager-server/src/test/resources/db/testdata.sql:/flyway/testdata/V4.0.0__insert-testdata.sql
# end::database[]

# tag::server[]
  customer-manager-server:
    build:
      context: .
    ports:
      - 8080:8080
# end::server[]
# tag::database-configuration[]
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: geheim
    depends_on:
      flyway:
        condition: service_completed_successfully
# end::database-configuration[]
